name: 'The Code Reviewer'
description: 'Automating code review using ChatGPT with Github Actions. Look for potential bugs and suggest code improvements in your PR'
branding:
  icon: 'arrow-up-right'
  color: 'orange'
inputs:
  openai-api-key:
    description: 'OpenAI API Key'
    required: true
    default: ''
  github-token:
    description: 'Github API Key'
    required: true
    default: ''
  github-pr-id:
    description: 'Github Pull Request ID'
    required: true
    default: ''
  openai-engine:
    description: 'GPT-4o models can understand and generate natural language with higher accuracy and capabilities.'
    required: false
    default: 'gpt-4o'
  openai-temperature:
    description: 'What sampling temperature to use. Higher values means the model will take more risks. Try 0.9 for more creative applications, and 0 (argmax sampling) for ones with a well-defined answer.'
    required: false
    default: '0.0'
  openai-max-tokens:
    description: 'The maximum number of tokens to generate in the completion.'
    required: false
    default: '4096'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.openai-api-key }}
    - ${{ inputs.github-token }}
    - ${{ inputs.github-pr-id }}
    - ${{ inputs.openai-engine }}
    - ${{ inputs.openai-temperature }}
    - ${{ inputs.openai-max-tokens }}
